In [1]:
import numpy as np

In [2]:
%matplotlib inline

In [3]:
from numpy.random import rand

In [4]:
num_samples = 2

In [5]:
num_features = 2

In [7]:
input = rand(num_samples, num_features)

In [8]:
input

array([[ 0.13053037,  0.98584811],
       [ 0.26820215,  0.82404461]])

In [9]:
from keras.models import Sequential

Using Theano backend.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN 5103)


In [46]:
model = Sequential()

In [47]:
from keras.layers import Dense, Activation

In [48]:
output = np.dot(input, [2,3]) + 5

In [49]:
output

array([ 8.21860508,  8.00853811])

In [50]:
model.add(Dense(1, input_shape=(num_features,)))
model.add(Activation('relu'))

In [51]:
from keras import optimizers
model.compile(loss='mse',
              optimizer=optimizers.SGD(lr=0.1))

In [52]:
model.evaluate(input, output)

2/2 [==============================] - 0s


65.726272583007812

In [61]:
model.fit(input, output, nb_epoch=10)

Epoch 1/10
2/2 [==============================] - 0s - loss: 0.0494
Epoch 2/10
2/2 [==============================] - 0s - loss: 0.0433
Epoch 3/10
2/2 [==============================] - 0s - loss: 0.0408
Epoch 4/10
2/2 [==============================] - 0s - loss: 0.0397
Epoch 5/10
2/2 [==============================] - 0s - loss: 0.0392
Epoch 6/10
2/2 [==============================] - 0s - loss: 0.0389
Epoch 7/10
2/2 [==============================] - 0s - loss: 0.0387
Epoch 8/10
2/2 [==============================] - 0s - loss: 0.0385
Epoch 9/10
2/2 [==============================] - 0s - loss: 0.0384
Epoch 10/10
2/2 [==============================] - 0s - loss: 0.0382


In [62]:
model.evaluate(input, output)

2/2 [==============================] - 0s


0.038060732185840607

In [59]:
model.predict(np.array([np.array([1,2])]))

array([[ 12.68881226]], dtype=float32)

In [63]:
model.get_weights()

[array([[ 0.3941955 ],
        [ 4.04350138]], dtype=float32), array([ 4.36861134], dtype=float32)]