In [44]:
import numpy as np

In [45]:
%matplotlib inline

In [46]:
from numpy.random import rand

In [47]:
from numpy.random import random_integers

In [48]:
num_samples = 30

In [49]:
num_features = 2

In [50]:
input = random_integers(low=1, high=5, size=(num_samples, num_features))

/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  if __name__ == '__main__':


In [51]:
input

array([[1, 4],
       [5, 5],
       [3, 3],
       [5, 1],
       [3, 3],
       [4, 4],
       [3, 5],
       [3, 5],
       [5, 2],
       [1, 2],
       [3, 4],
       [4, 3],
       [1, 5],
       [5, 1],
       [5, 1],
       [4, 4],
       [3, 3],
       [2, 4],
       [4, 1],
       [4, 1],
       [4, 4],
       [5, 5],
       [2, 5],
       [1, 4],
       [5, 4],
       [5, 1],
       [1, 3],
       [4, 2],
       [4, 3],
       [5, 3]])

In [90]:
from keras.models import Sequential
from keras.optimizers import SGD, RMSprop
from keras.layers import Dense, Activation

In [91]:
lm = Sequential([ Dense(1, input_shape=(2,)) ])
lm.compile(optimizer=SGD(lr=1), loss='mse')

In [92]:
output = np.dot(input, [2,3]) + 1

In [93]:
output

array([15, 26, 16, 14, 16, 21, 22, 22, 17,  9, 19, 18, 18, 14, 14, 21, 16,
       17, 12, 12, 21, 26, 20, 15, 23, 14, 12, 15, 18, 20])

In [94]:
#model.add(Dense(1, input_shape=(num_features,)))
#model.add(Activation('relu'))

In [95]:
lm.evaluate(input, output)

30/30 [==============================] - 0s


399.7200927734375

In [96]:
lm.fit(input, output, nb_epoch=5, batch_size=1)

Epoch 1/5
30/30 [==============================] - 0s - loss: nan          
Epoch 2/5
30/30 [==============================] - 0s - loss: nan     
Epoch 3/5
30/30 [==============================] - 0s - loss: nan     
Epoch 4/5
30/30 [==============================] - 0s - loss: nan     
Epoch 5/5
30/30 [==============================] - 0s - loss: nan     


In [97]:
lm.evaluate(input, output)

30/30 [==============================] - 0s


nan

In [98]:
lm.predict(np.array([np.array([1,2])]))

array([[ nan]], dtype=float32)

In [34]:
lm.get_weights()

[array([[-43.66954803],
        [-32.58183289]], dtype=float32), array([-16.50037766], dtype=float32)]

In [100]:
from numpy.random import random, permutation
x = random((30,2))
y = np.dot(x, [2., 3.]) + 1.

In [101]:
lm = Sequential([ Dense(1, input_shape=(2,)) ])
lm.compile(optimizer=SGD(lr=0.1), loss='mse')

In [102]:
lm.evaluate(x, y, verbose=0)

8.0683860778808594

In [103]:
lm.fit(x, y, nb_epoch=5, batch_size=1)

Epoch 1/5
30/30 [==============================] - 0s - loss: 0.8020     
Epoch 2/5
30/30 [==============================] - 0s - loss: 0.0810     
Epoch 3/5
30/30 [==============================] - 0s - loss: 0.0313     
Epoch 4/5
30/30 [==============================] - 0s - loss: 0.0122     
Epoch 5/5
30/30 [==============================] - 0s - loss: 0.0049     


In [104]:
lm.get_weights()

[array([[ 2.00559092],
        [ 2.8249321 ]], dtype=float32), array([ 1.11946535], dtype=float32)]